MODEL_CONFIG:  
  OBJECT_DETECTION_MODEL:
    CONFIG:
      DATALOADER:
        NUM_WORKERS: 4
      SOLVER:
        IMS_PER_BATCH: 2
        BASE_LR: 0.001
        MAX_ITER: 10
      MODEL:
        ROI_HEADS:
          BATCH_SIZE_PER_IMAGE: 32
          NUM_CLASSES: 14

  TEXT_DETECTION_MODEL:
    CONFIG:
      WEIGHTS: R-101.pkl
      SOLVER:
        MAX_ITER: 10
      

      
  